# Generated by Django 6.1 on 2026-09-29 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("igot", "iGOT Karmayogi"),
                            ("tpac", "TPAC"),
                            ("local", "ORBIS Local"),
                        ],
                        max_length=50,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("courses_added", models.IntegerField(default=0)),
                ("courses_updated", models.IntegerField(default=0)),
                ("status", models.CharField(default="success", max_length=20)),
                ("error_message", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("igot", "iGOT Karmayogi"),
                            ("tpac", "TPAC"),
                            ("local", "ORBIS Local"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="Unique identifier from the provider system",
                        max_length=255,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                ("duration_minutes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competencies",
                    models.ManyToManyField(
                        blank=True, related_name="courses", to="core.competency"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("provider", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="Enrolment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="enrolled",
                        max_length=20,
                    ),
                ),
                ("progress_percent", models.IntegerField(default=0)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("last_accessed_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolments",
                        to="catalog.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-enrolled_at"],
                "unique_together": {("user", "course")},
            },
        ),
    ]
