import uuid
from django.db import models
from apps.accounts.models import OfficialProfile
from apps.competency.models import Competency

class CompetencyLab(models.Model):
    """
    A scenario-based lab that evaluates a specific competency.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    competency = models.ForeignKey(Competency, on_delete=models.CASCADE, related_name='labs')
    
    title = models.CharField(max_length=255)
    description = models.TextField(help_text="The briefing/scenario for the user.")
    
    environment_type = models.CharField(max_length=50, choices=[
        ('python_notebook', 'Python Data Analysis'),
        ('sql_terminal', 'SQL Database Query'),
        ('policy_canvas', 'Policy Writing Canvas')
    ])
    
    evaluation_rubric = models.TextField(help_text="Instructions for the LLM on how to score this lab out of 100.")
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.title} ({self.environment_type})"


class LabSession(models.Model):
    """
    A specific instance of an official attempting a lab.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    lab = models.ForeignKey(CompetencyLab, on_delete=models.CASCADE, related_name='sessions')
    official = models.ForeignKey(OfficialProfile, on_delete=models.CASCADE, related_name='lab_sessions')
    
    user_input = models.TextField(help_text="The code or text submitted by the user.", blank=True)
    
    llm_score_raw = models.FloatField(null=True, blank=True)
    llm_feedback = models.TextField(blank=True, help_text="Feedback generated by the LLM evaluator.")
    
    status = models.CharField(max_length=20, choices=[
        ('in_progress', 'In Progress'),
        ('evaluating', 'Evaluating'),
        ('completed', 'Completed')
    ], default='in_progress')
    
    created_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.official} - {self.lab.title} ({self.status})"
