import uuid
from django.db import models
from apps.accounts.models import OfficialProfile
from apps.competency.models import Competency

class CompetencyLab(models.Model):
    """
    A scenario-based experiential lab that evaluates a specific competency.
    Supports:
    - crisis_simulation: Branching scenario with real-time decision-making and consequences
    - data_detective: Interactive synthetic microdata audit and defect identification
    - python_notebook: Real Python script execution with Pandas/Numpy
    - sql_terminal: SQL database queries and discrepancy analysis
    - policy_canvas: Policy draft / governance protocol writing
    """
    ENVIRONMENT_CHOICES = [
        ('crisis_simulation', 'Statistical Crisis Simulation (Branching)'),
        ('data_detective', 'Data Detective (Microdata Audit)'),
        ('python_notebook', 'Python Data Analysis'),
        ('sql_terminal', 'SQL Database Query'),
        ('policy_canvas', 'Policy Writing Canvas'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    competency = models.ForeignKey(Competency, on_delete=models.CASCADE, related_name='labs')
    
    title = models.CharField(max_length=255)
    description = models.TextField(help_text="The briefing/scenario for the user.")
    
    environment_type = models.CharField(max_length=50, choices=ENVIRONMENT_CHOICES)
    scenario_data = models.JSONField(default=dict, blank=True, help_text="Structured stages, datasets, or branching decision trees")
    
    evaluation_rubric = models.TextField(help_text="Instructions for the rubric evaluation on how to score this lab out of 100.")
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.title} ({self.environment_type})"


class LabSession(models.Model):
    """
    A specific instance of an official attempting an experiential lab.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    lab = models.ForeignKey(CompetencyLab, on_delete=models.CASCADE, related_name='sessions')
    official = models.ForeignKey(OfficialProfile, on_delete=models.CASCADE, related_name='lab_sessions')
    
    user_input = models.TextField(help_text="The code, text, or final decisions submitted by the user.", blank=True)
    session_state = models.JSONField(default=dict, blank=True, help_text="State machine transitions, branching paths, decisions chosen")
    
    llm_score_raw = models.FloatField(null=True, blank=True)
    llm_feedback = models.TextField(blank=True, help_text="Feedback generated by the evaluator.")
    
    status = models.CharField(max_length=20, choices=[
        ('in_progress', 'In Progress'),
        ('evaluating', 'Evaluating'),
        ('completed', 'Completed')
    ], default='in_progress')
    
    created_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.official} - {self.lab.title} ({self.status})"
