# Generated by Django 5.1.15 on 2026-09-29 11:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('competency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('knowledge_assessment', 'Knowledge Assessment'), ('competency_lab', 'Experiential Competency Lab'), ('virtual_lab', 'Virtual Lab (Python/SQL)'), ('course_completion', 'Course Completion Context'), ('manual_review', 'Manual Review / Interview')], max_length=50)),
                ('source_reference', models.CharField(blank=True, help_text='ID or link to the specific lab/quiz', max_length=255)),
                ('score_raw', models.FloatField(help_text='Raw percentage or points (e.g. 72.5)')),
                ('score_proficiency', models.IntegerField(help_text='Mapped to 1-5 ORBIS proficiency scale')),
                ('explanation', models.TextField(help_text='Deterministic explanation of why this score was given')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='competency.competency')),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='accounts.officialprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OfficialCompetencyScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_proficiency', models.IntegerField(default=0, help_text='Current aggregated level 1-5')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_scores', to='competency.competency')),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_scores', to='accounts.officialprofile')),
            ],
            options={
                'unique_together': {('official', 'competency')},
            },
        ),
    ]
