# Generated by Django 5.1.15 on 2026-09-29 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(help_text='Short code, e.g. MOSPI, CSO', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(help_text='Short code, e.g. SO, DSO, DD', max_length=50, unique=True)),
                ('level', models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('leadership', 'Leadership')], default='entry', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_roles', to='accounts.department')),
            ],
            options={
                'ordering': ['level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OfficialProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('official', 'Official / Learner'), ('trainer', 'Trainer'), ('admin', 'Administrator')], default='official', max_length=20)),
                ('designation', models.CharField(blank=True, default='', max_length=255)),
                ('employee_id', models.CharField(blank=True, default='', help_text='Government employee ID (for demo / SSO simulation)', max_length=100, unique=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officials', to='accounts.department')),
                ('job_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officials', to='accounts.jobrole')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orbis_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
