# Generated by Django 5.1.15 on 2026-09-29 11:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('competency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyLab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='The briefing/scenario for the user.')),
                ('environment_type', models.CharField(choices=[('python_notebook', 'Python Data Analysis'), ('sql_terminal', 'SQL Database Query'), ('policy_canvas', 'Policy Writing Canvas')], max_length=50)),
                ('evaluation_rubric', models.TextField(help_text='Instructions for the LLM on how to score this lab out of 100.')),
                ('is_active', models.BooleanField(default=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='competency.competency')),
            ],
        ),
        migrations.CreateModel(
            name='LabSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_input', models.TextField(blank=True, help_text='The code or text submitted by the user.')),
                ('llm_score_raw', models.FloatField(blank=True, null=True)),
                ('llm_feedback', models.TextField(blank=True, help_text='Feedback generated by the LLM evaluator.')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('evaluating', 'Evaluating'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='labs.competencylab')),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_sessions', to='accounts.officialprofile')),
            ],
        ),
    ]
