# Generated by Django 5.1.15 on 2026-09-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencylab',
            name='scenario_data',
            field=models.JSONField(blank=True, default=dict, help_text='Structured stages, datasets, or branching decision trees'),
        ),
        migrations.AddField(
            model_name='labsession',
            name='session_state',
            field=models.JSONField(blank=True, default=dict, help_text='State machine transitions, branching paths, decisions chosen'),
        ),
        migrations.AlterField(
            model_name='competencylab',
            name='environment_type',
            field=models.CharField(choices=[('crisis_simulation', 'Statistical Crisis Simulation (Branching)'), ('data_detective', 'Data Detective (Microdata Audit)'), ('python_notebook', 'Python Data Analysis'), ('sql_terminal', 'SQL Database Query'), ('policy_canvas', 'Policy Writing Canvas')], max_length=50),
        ),
        migrations.AlterField(
            model_name='competencylab',
            name='evaluation_rubric',
            field=models.TextField(help_text='Instructions for the rubric evaluation on how to score this lab out of 100.'),
        ),
        migrations.AlterField(
            model_name='labsession',
            name='llm_feedback',
            field=models.TextField(blank=True, help_text='Feedback generated by the evaluator.'),
        ),
        migrations.AlterField(
            model_name='labsession',
            name='user_input',
            field=models.TextField(blank=True, help_text='The code, text, or final decisions submitted by the user.'),
        ),
    ]
