# Generated by Django 5.1.15 on 2026-09-29 10:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Competency Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='Short identifier e.g. STAT-SD', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='competency.competencycategory')),
            ],
            options={
                'verbose_name_plural': 'Competencies',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoleRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_proficiency', models.IntegerField(choices=[(1, 'Basic'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert'), (5, 'Master')], default=2, help_text='The required proficiency level (1-5) for this role.')),
                ('weight', models.FloatField(default=1.0, help_text='Importance multiplier for this role (e.g., 1.5 for core skill, 0.5 for secondary)')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requirements', to='competency.competency')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_requirements', to='accounts.jobrole')),
            ],
            options={
                'ordering': ['job_role__title', 'competency__name'],
                'unique_together': {('job_role', 'competency')},
            },
        ),
    ]
